### ISSUE TITLE
MySQL and PostgreSQL modules not up-to-date

### ISSUE THREAD

**Issue by jeremyrickard** [Azure/open-service-broker-azure#381]
The MySQL and PostgreSQL services have become GA now. Along with this, there were some changes to the ARM template structure/capabilities. We are using the older preview API and the associated template. We should update to the newer version in order to expose those additional capabilities (geo replicated backup) to customers. 

Additionally, it looks like the pricing model has changed. We currently pin certain storage amounts to a SKU and that looks like it has changed, along with available hardware types and numbers of cores available. We should update the provisioning parameters to accommodate this.

**Comment by yokawasa** [comment]
I'm not  sure if it's relevant but no matter how many time i tried to create MySQL or PosgreSQL instance by following [manual](https://github.com/Azure/open-service-broker-azure/blob/master/docs/modules/postgresql.md) in this repo, I always see 'OrphanMitigation' status and never get 'Ready'. I almost giving up using osba.  

```
svcat get instances
                   NAME                    NAMESPACE        CLASS          PLAN          STATUS
+----------------------------------------+-----------+------------------+---------+------------------+
  example-postgresql-all-in-one-instance   default     azure-postgresql   basic50   OrphanMitigation
```

**Comment by krancour** [comment]
@yokawasa, what version of OSBA are you using? Can you show us some logs from OSBA when that occurs? It should be pretty obvious to us what's going on. Would love to help you out.

**Comment by yokawasa** [comment]
@krancour  thank you.
I'm running this on AKS (cluster v1.9.1 ), and I'm using `open-service-broker-azure-0.10.0`.  Here is the logs from osba when I had error:
```
time="2018-04-18T20:27:14Z" level=error msg="error executing job; not submitting any follow-up tasks" error="error executing deprovisioning step \"deleteARMDeployment\" for instance \"dd4a60a6-4346-11e8-8de3-0a580af40011\": error executing deprovisioning step: error deleting ARM deployment: error deleting deployment \"ca9b24eb-7ca2-4d97-bd67-da309c30ed6e\" from resource group \"rg-osba\": resources.DeploymentsClient#Delete: Failure sending request: StatusCode=403 -- Original Error: Code=\"AuthorizationFailed\" Message=\"The client '5da04d89-9a77-480b-9807-c4b11ecd676d' with object id '5da04d89-9a77-480b-9807-c4b11ecd676d' does not have authorization to perform action 'Microsoft.Resources/deployments/delete' over scope '/subscriptions/87c7c7f9-0c9f-47d1-a856-1305a0cbfd7a/resourcegroups/rg-osba/providers/Microsoft.Resources/deployments/ca9b24eb-7ca2-4d97-bd67-da309c30ed6e'.\"" job=executeDeprovisioningStep taskID=713c7931-64ba-49ea-962d-c74d37c8b1c4
```
It looks like service principal errror but I'm actually using right one with which i was able to create AKS cluster.

**Comment by johnhamelink** [comment]
I am also ending up with the "OrphanMitigation" state, however for me the problem was that the postgres instance I am creating has not had the k8s clusters' IP whitelisted. Here's the log in `open-service-broker-azure`'s logs:

```
time="2018-04-18T21:10:48Z" level=error msg="error executing job; not submitting any follow-up tasks" error="error executing provisioning step \"setupDatabase\" for instance \"1b313286-434c-11e8-9b43-0a580af40124\": error executing provisioning step: error starting transaction: pq: no pg_hba.conf entry for host \"<redacted>\", user \"postgres\", database \"postgres\", SSL on" job=executeProvisioningStep taskID=f27e56b8-49d7-4b7c-95b3-c1e4c2312f5f
```

**Comment by jeremyrickard** [comment]
@johnhamelink thanks for the data point! Are you running this on AKS or an unmanaged K8s cluster on Azure? We made the decision a while back to by default set these resources (MySQL, PostgreSQL, SQLDB etc) to default to Azure only firewall rules. This is more secure by default, but requires some changes if you're going to be running OSBA off of an Azure resource. So two related questions if you can provide info:

1.) If you were running this off of Azure, did you specify more permissive firewall rules
2.) If you were on Azure, could you share your config.

If you have your provisioning parameters that would be helpful too, I can open up a followup issue in the repo here. Also, please feel free to open issues when you come across anything like this and we'll investigate!

**Comment by johnhamelink** [comment]
@jeremyrickard no problem!

>  Are you running this on AKS or an unmanaged K8s cluster on Azure?

AKS with kubernetes 1.9.3

> If you were running this off of Azure, did you specify more permissive firewall rules

My firewall rules looked like this:

```
    firewallRules:
      - name: LocalAccess
        startIPAddress: 10.0.0.0
        endIPAddress: 10.255.255.255
```

I had to also add the Public IP of the k8s node to the config to get it to the "ready" state.

> If you were on Azure, could you share your config.

Sure!

```
{{ if eq .Values.environment.isDev false }}
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: postgres
  namespace: staging                                         # The namespace the instance is exposed within
spec:
  clusterServiceClassExternalName: azure-postgresql          # The type of resource to provision (use 'svcat get classes' to find the one you want)
  clusterServicePlanExternalName: basic50                    # The size/scale of the resource    (use 'svcat get plans' to find the one you want)
  parameters:
    location: eastus                                         # Which datacenter to use
    resourceGroup: <redacted>                                # Which resource group to put the resource in
    sslEnforcement: disabled
    firewallRules:
      - name: LocalAccess
        startIPAddress: 10.0.0.0
        endIPAddress: 10.255.255.255
      - name: k8sMaster
        startIPAddress: <k8s public ip>
        endIPAddress: <k8s public ip>
{{ end }}
```
