### ISSUE TITLE
standard or premium plan azure-service bus fails to provision

### ISSUE THREAD

**Issue by timwebster9** [Azure/open-service-broker-azure#571]
If I try and provision a Service Bus with plan of `standard` or `premium`, it fails with this error:

```
  Status:      Failed - Error provisioning ServiceInstance of ClusterServiceClass (K8S: "6dc44338-2f13-4bc5-9247-5b1b3c5462d3" ExternalName: "azure-servicebus") at ClusterServiceBroker "osba": Status: 400; ErrorMessage: ValidationError; Description: The value provided for location is invalid: unrecognized field; ResponseError: <nil> @ 2018-09-18 16:48:51 +0000 UTC
  Class:       azure-servicebus
  Plan:        standard
```

Using the `basic` plan it works fine. 

I'm using this yaml with kubectl:

```
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: servicebus-service-instance
  namespace: rhubarb
spec:
  clusterServiceClassExternalName: azure-servicebus
  clusterServicePlanExternalName: standard
  parameters:
    location: 'uksouth'
    resourceGroup: 'timw-aks-rg'
---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: servicebus-binding
  namespace: rhubarb
spec:
  instanceRef:
    name: servicebus-service-instance
  secretName: servicebus-secret
```
