### ISSUE TITLE
env var valueFrom.secretKeyRef not expanded in other env var or args 

### ISSUE THREAD

**Issue by cforce** [Azure/open-service-broker-azure#677]
Is there and hint how to use the created secrets of the binding towards applications running in pods.?
All for me known ways seems not work on AKS- please give advice.
https://github.com/Azure/AKS/issues/836

**Comment by zhongyi-zhang** [comment]
The AKS quick-start guidance has an example for installing WordPress by Helm chart: https://github.com/Azure/open-service-broker-azure/blob/master/docs/quickstart-aks.md
Here are more Helm chart examples: https://github.com/Azure/helm-charts.

Is it what you look for?

**Comment by cforce** [comment]
Not exatcly. I still cant find a way how i pass the generated secret key value into an java enviroment variable or arg param . I can't use the same value as used in the param "URI" of the secret value, but need to prefix "jdbc:" before i pass it in. 
I would be able to change the URI=jdbdc:$URI value already when creating the binding or add a new param to the binding like URL=jdbdc:$URI  that work also,
Currently i amusing 
svcat bind ups-instance --name ups-binding to create the binding.

**Comment by zhongyi-zhang** [comment]
```
- name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: my-app-mysql-secret
              key: uri
- name: DATABASE_JDBC
          value: "jdbc:$(DATABASE_URI)"
```
Does something like this work? I found https://stackoverflow.com/questions/40889743/string-operation-on-env-variables-on-kubernetes, it seems string operator is doable.
