### ISSUE TITLE
adminAccountSettings  - unrecognized field

### ISSUE THREAD

**Issue by ivanov-aleksander** [Azure/open-service-broker-azure#716]
I tried create ServiceInstance of azure-postgresql-10 and specify adminAccountSettings like adminUsername and adminPassword but I faced an error.
"osba": Status: 400; ErrorMessage: ValidationError; Description: The value provided for adminAccountSettings is invalid: unrecognized field; ResponseError: <nil>"

```yaml
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: sonarqube-postgresql
spec:
  clusterServiceClassExternalName: azure-postgresql-10
  clusterServicePlanExternalName: general-purpose
  parameters:
    adminAccountSettings:
      adminPassword: somepassword
      adminUsername: sonaruser
    location: westeurope
    resourceGroup: test
    firewallRules:
    - startIPAddress: "0.0.0.0"
      endIPAddress: "255.255.255.255"
      name: "AllowAll"
```
